plugin-type: group
group-name: argo-workflow
plugins:
  - name: argo-workflow
    enabled: true
inline-plugins:
  - plugin-name: kubeflow-bind-traefik
    yaml:
      - url: "https://raw.githubusercontent.com/kf5i/k3ai-plugins/main/common/traefik/kubeflow-pipeline-bind.yaml"