name: Approved Labels

on: [issue_comment]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ contains(github.event.comment.body, '/approved') }} || ${{ contains(github.event.comment.body, '/roadmap') }}
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          labels: |
            needs-triage
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.comment.body, '/roadmap') }}
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          labels: |
            roadmap
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.comment.body, '/approved') }}
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          labels: |
            roadmap



