name: Community
on: 
  issues:
    types: [opened, created, reopened]
  pull_request_target:
    types: [opened]

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            needs-triage
            enhancement
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
