name: Actions
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: [edited]

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Label Actions
        uses: hramos/label-actions@v1
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
