# This is a basic workflow to help you get started with Actions
name: Auto Assign to Project(s)

on:
  issues:
    types: [created,opened,reopened,edited]
  pull_request:
    types: [created,opened,reopened,edited]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    #Issue's
    - uses: actions/checkout@v2
    - uses: actions-ecosystem/action-add-labels@v1
      if:  contains(github.event.issue.title, '[feat:]')
      with:
        labels: |
          needs-triage
          enhancement
    - uses: bubkoo/auto-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        issuesOpenedReactions: 'hooray, +1'
        issuesOpenedComment: >
          👋 @{{ author }}

          Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
          Please make sure you have given us as much context as possible.
    - uses: srggrs/assign-one-project-github-action@1.2.0
      if:  contains(github.event.issue.title, '[feat:]')
      with:
        project: 'https://github.com/orgs/kf5i/projects/2'
        column_name: 'Features Requests'
    - uses: actions/checkout@v2
    - uses: actions-ecosystem/action-add-labels@v1
      if:  contains(github.event.issue.title, '[bug:]')
      with:
        labels: |
          bug
    - uses: bubkoo/auto-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        issuesOpenedReactions: 'eyes, +1'
        issuesOpenedComment: >
          👋 @{{ author }}

          Thank you for raising a bug. We will investigate into the matter and get back to you as soon as possible.
          Please make sure you have given us as much context as possible.

    #PR's are always opened in the "In Progress" column
    - uses: srggrs/assign-one-project-github-action@1.2.0
      if:  contains(github.event.pull_request.title, '[feat:]')
      with:
        project: 'https://github.com/orgs/kf5i/projects/2'
        column_name: 'In Progress'
    - uses: actions/checkout@v2
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: |
          approved
          enhancement


        
